name: Deploy Python backend to AWS Lambda
on: [push]
jobs:
  cypress-run-job:
    name: cypress-API-testing
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install node
        uses: actions/setup-node@v2
        with:
          node:version: "14"
          config-file: cypress.config.js
      - name: Install dependencies
        run: npm install
      - name: Cypress run
        uses: cypress-io/github-action@v2

  deploy-source-job:
    needs: cypress-run-job
    name: Deploy lambda function from source
    runs-on: ubuntu-latest
    steps:
      - name: checkout source code
        uses: actions/checkout@v3
      - name: default deploy
        uses: appleboy/lambda-action@v0.1.9
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}
          function_name: myVisitCounter
          source: app.py
